[build]
  publish = "."
  
[[redirects]]
  from = "/api/*"
  to = "https://gost-assistant-backend.onrender.com/api/:splat"
  status = 200
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    